//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 地铁售票系统.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string StartStation { get; set; }
        public string EndStation { get; set; }
        public int TicketsNum { get; set; }
        public System.DateTime Time { get; set; }
        public decimal Money { get; set; }
        public int StartTag { get; set; }
        public int EndTag { get; set; }
        public string TicketsState { get; set; }
        public string LineNumber { get; set; }
    
        public virtual UserInfoes UserInfoes { get; set; }
    }
}
